---
- name: Download S3 Server file to local
  s3_file_transfer:
    endpoint_url: "{{ s3_endpoint_url }}"
    ak: "{{ s3_ak }}"
    sk: "{{ s3_sk }}"
    src: "my-bucket/sub-bucket1/zabbix_agentd.log"
    dest: "/root/zabbix_agentd.log"
    state: "download"
